version: 2.1
orbs: 
  aws-cli: circleci/aws-cli@3.1.1

jobs:
  test:
    docker:
      - image: cimg/node:18.15.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Configure git
          command: |
            git config user.name "Senor Mann"
            git config user.email "senormann@email.com"
      - run:
          environment:
            HUSKY_DEBUG: 1
          name: build
          command: |
            npm version 0.0.1
            ls -a
workflows:
  main:
    when:
      and:
        - equal: [test, << pipeline.git.branch >>]
    jobs:
      - test